### ISSUE TITLE
Options Not Saved

### ISSUE THREAD

**Issue by markwr** [bobbyrne01/save-text-to-file-firefox#101]
When I make changes to this extension's Options screen, and then click Save, it does not save (I confirm that later when I come back to that Options screen). Using Firefox 66.0.3 (64-bit). Disabled other extensions.

**Comment by markwr** [comment]
I can now save options (I had a few extensions still loaded, I'll try to figure out which was the conflict).

**Comment by markwr** [comment]
I re-opened this issue because the symptom has come back, even with no other extensions installed. I even uninstalled and reinstalled this extension. The problem still exists.

**Comment by bobbyrne01** [comment]
Hey @markwr Could you please retest using the latest version of the extension? And reopen if issue still persists. If the issue is still present, could you copy/paste the logs from the browser console, thanks.

**Comment by markwr** [comment]
Bob,
Seems to work fine now. Thanks!

    On Wednesday, October 2, 2019, 10:56:03 AM EDT, Robert Byrne <notifications@github.com> wrote:  
 
 
Closed #101.
