### ISSUE TITLE
Filename empty

### ISSUE THREAD

**Issue by markwr** [bobbyrne01/save-text-to-file-firefox#102]
No matter how I set the options, I always get an error when I try to save highlighted text to a file via right-click:
"Save text to file. Error: Filename cannot be empty, please review preferences".
![Save text to file Error](https://user-images.githubusercontent.com/17146589/56856903-f9b23d80-6932-11e9-9118-d9ee3a7d1d51.jpg)

**Comment by markwr** [comment]
I tried uninstalling and then reinstalling this extension (no other extensions active). The error message no longer pops up, but the file is not saved to disk (nowhere that I can find it anyway, for sure no file with a .txt extension was saved with a recent time stamp on either of my hard drive partitions).

**Comment by bobbyrne01** [comment]
hey @markwr Could you please retest using the latest version?

Also if the issue still arises, could you take a screenshot of the options page? So I could try reproduce, thanks
