### ISSUE TITLE
saving text from local pdf files

### ISSUE THREAD

**Issue by anyboby** [bobbyrne01/save-text-to-file-firefox#104]
Hi, 
is there currently a possibility to save selected text from locally opened pdf files in the browser, .e.g by editing the permissions ?

As of now, the extension does not save any textfiles when viewing pdfs in the embedded viewer 

Thanks in advance !

**Comment by bobbyrne01** [comment]
@anyboby @Dboingue This works in latest version 4.2.5

https://addons.mozilla.org/en-GB/firefox/addon/save-text-to-file/
