### ISSUE TITLE
Options dropdown for 'If file exists', does not display latest selection for Append/Overwrite

### ISSUE THREAD

**Issue by minshifu** [bobbyrne01/save-text-to-file-firefox#106]
Hello, Save Behavior keeps reverting to "Overwrite" each time even after I chose "Append" and saved. Pls check it. Thank you!

**Comment by bobbyrne01** [comment]
@minshifu Append is working as expected for me. Please see [this](https://www.youtube.com/watch?v=blDZjYBfvvE) video demo.

**Comment by minshifu** [comment]
Yes,the appending function works. But the dropdown menu only shows Overwrite even after Append was chosen and saved.

**Comment by bobbyrne01** [comment]
Ah ok, so its specific to the options dropdown. At least functionally its working.

Will fix _dropdown not displaying latest selection_ soon.

**Comment by thaihbn** [comment]
Is there still an option for Append file if file exists? I can not find this option. This is the only thing I want to use this add on. Please help.

**Comment by bobbyrne01** [comment]
@minshifu  This is fixed in 4.2.5

https://addons.mozilla.org/firefox/addon/save-text-to-file/

`Append`/`Overwrite` dropdown displays latest selection

**Comment by minshifu** [comment]
> 
> 
> @minshifu This is fixed in 4.2.5
> 
> https://addons.mozilla.org/firefox/addon/save-text-to-file/
> 
> `Append`/`Overwrite` dropdown displays latest selection

Thank you so much!
