### ISSUE TITLE
Text file encoding changing from ASCI default

### ISSUE THREAD

**Issue by Dboingue** [bobbyrne01/save-text-to-file-firefox#107]
It appears that my Firefox latest as of this writing, and this extension, use ANSI as text file encoding by default.  Is there a way to use utf8 instead?

**Comment by niccnocc** [comment]
I'm experiencing the same problem.
Please answer
@Dboingue did you get any feedback for your question? If so, could you please forward the answer to me? Thanks!
@bobbyrne01 
@eson57 
@chille07

**Comment by Dboingue** [comment]
I did not receive any answer.  And this is still happening.

**Comment by niccnocc** [comment]
That's a pity :| 
thanks anyway for your answer!
did you find anything in Firefox? 
cheers

**Comment by niccnocc** [comment]
That's a pity :|
thanks anyway for your answer!
did you find anything in Firefox?
cheers @Dboingue

**Comment by bobbyrne01** [comment]
@Dboingue @niccnocc This is fixed in 4.2.3

https://addons.mozilla.org/en-GB/firefox/addon/save-text-to-file/

`UTF-8` is now default encoding.
