### ISSUE TITLE
Save Text To File not working w/ Firefox

### ISSUE THREAD

**Issue by lw108** [bobbyrne01/save-text-to-file-firefox#108]
Hi,

Save Text to File stopped working with Firefox. It works w/ Brave. I tested it with each of my extensions disabled on a web page / text section that worked in Brave. Can you tell me what Firefox settings and/or extensions may prevent it from working?

Thanks

**Comment by bobbyrne01** [comment]
Please try the latest version 4.2.4, working for me in Firefox:

https://addons.mozilla.org/en-GB/firefox/addon/save-text-to-file/

There is no official list of extensions that may conflict (yet)
