### ISSUE TITLE
Good but now you can't save from many sites, e.g. IMDb :\ And in the reader view, nothing ... 

### ISSUE THREAD

**Issue by simonjanosbalint** [bobbyrne01/save-text-to-file-firefox#109]
Good but now you can't save from many sites, e.g. IMDb :\ And in the reader view, nothing ...

**Comment by bobbyrne01** [comment]
@simonjanosbalint Both scenarios are working for me using version 4.2.4

https://addons.mozilla.org/firefox/addon/save-text-to-file/
