### ISSUE TITLE
No dialog window to specify where to save

### ISSUE THREAD

**Issue by blogdemoi** [bobbyrne01/save-text-to-file-firefox#110]
Hi,

I am a happy user (on Firefox 92 Linux Manjaro Xfce), used your addon for a few years (without the app). Today I decided to install the app, I followed the installation guide and the app is detected as installed in the preferences.

However, there is no window showing when saving to specify where to save, so it always saves on the desktop (the path I indicated in the settings).

The funny part is that before installing the application, I had a window asking me where to save the file, but after the app install, no more.

Thank you for any advises.

**Comment by bobbyrne01** [comment]
I see the same behaviour , which version of python are you using @blogdemoi ?

**Comment by bobbyrne01** [comment]
@blogdemoi Updated, to show a directory selection dialog if option enabled. 

Can you retry using latest versions of extension and app?

Extension `4.3.0`:
https://addons.mozilla.org/firefox/addon/save-text-to-file/

App `0.3.0`:
https://github.com/bobbyrne01/save-text-to-file-firefox/blob/master/app/savetexttofile.py#L24

**Comment by blogdemoi** [comment]
> Can you retry using latest versions of extension and app?

Thank you very much it is working fine now. I use you addon a lot, very handy. Adding the possibility to create a folder when saving would be nice too...
