### ISSUE TITLE
Each save doubles space between saves

### ISSUE THREAD

**Issue by AlexCeed** [bobbyrne01/save-text-to-file-firefox#70]
I use a central note.txt file within dropbox. This  file is used by notepad++ and your addon at the same time.
With no option checked in the addon, this is the problem:

I save the text "I am Charlie Wilson" in a new text file.
Here's the output:
            CRLF
            I am Charlie Wilson
            CRLF

If I copy the same thing again, I get:
            CRLF
            CRLF
            CRLF
            I am Charlie Wilson
            CRLF
            CRLF
            I am Charlie Wilson
            CRLF
            CRLF

And basically does this on every empty line. Wherever it sees CRLF it doubles, tripples it. 
The first time I encoutered this I was scared out of my wits; a file with only 50 lines of text had 10.000 lines!

**Comment by bobbyrne01** [comment]
@AlexCeed Thanks for reporting this issue!

I've reproduced it on Windows, will look at a fix soon.

**Comment by coreyp** [comment]
I'm having the same issue on OS X 10.10.3 with various editors.

**Comment by bobbyrne01** [comment]
have some free time coming up soon so hope to get to this, this week.

**Comment by bobbyrne01** [comment]
Can you retest after upgrading to version `2.7.1`?
