### ISSUE TITLE
Formatting issue

### ISSUE THREAD

**Issue by megnificentt** [bobbyrne01/save-text-to-file-firefox#73]
I recently started having an issue where multiple lines would appear between lines of data when putting the data from the txt file into Excel. 
For example, data appears as:
![1](https://cloud.githubusercontent.com/assets/10874342/6072311/dd81604c-ad65-11e4-83c2-ffbbca09451a.png)

But should appear as:
![2](https://cloud.githubusercontent.com/assets/10874342/6072310/dd7b9ad6-ad65-11e4-86b7-2a17843ac299.png)

I started using v2.4.6, which fixed the issue above, but now that v2.6.3 has come out, I have had to reinstall v2.4.6 every time I save text to file. I am having the same issue as describe above with v2.6.3. 
Any suggestions on how to make v2.4.6 my default/primary version, or how to fix the issue described?

Thanks!

**Comment by megnificentt** [comment]
Is there any update on this?

**Comment by bobbyrne01** [comment]
Might have same root cause as #70 

Going to try reproduce, should be fixable in v2.6.5

**Comment by bobbyrne01** [comment]
Can you retest after upgrading to version `2.7.1`?
