### ISSUE TITLE
ability to call save-text-to-file from html

### ISSUE THREAD

**Issue by opodecano** [bobbyrne01/save-text-to-file-firefox#74]
Ability to call save-text-to-file from html, its posible add this feature?
example.. when im press a button called "NNN" save text selected..
Regards.-

**Comment by bobbyrne01** [comment]
hey @opodecano 
Are you requesting the ability to save raw `HTML` text from a page? If so, that functionality is already available in v2.6.3.

If not, could you please provide a more detailed use case? thanks.

See screenshot below, notice the arrow pointing to 'Save selected html text' ..

![selection_033](https://cloud.githubusercontent.com/assets/1746110/6210698/0ff5ded8-b5ca-11e4-95a7-6b9d1e627e9d.png)

**Comment by opodecano** [comment]
Sorry about my bad english.
![screenshot_1](https://cloud.githubusercontent.com/assets/11027530/6210831/f83f5af0-b5a9-11e4-89d5-739f2053cf00.png)
is the ability to call "save-text-to-file extension" from the html code, if its posible?
the reason is i use Imacros to do repetitive consults to web, but it cant save text in a file, i think can combine it with save-text-to-file.

**Comment by bobbyrne01** [comment]
Outside scope of future changes.
