### ISSUE TITLE
Save as HTML with target url and title tag

### ISSUE THREAD

**Issue by Null-Kelvin** [bobbyrne01/save-text-to-file-firefox#75]
I'm really bad at coding, so I just changed .csv file saving and datestampinline function in Chrome.js

It's here 

fileName = (Preference.get('format') === 0 ?
        Utils.sanitizeFilename(fileName) + ".txt" : Utils.sanitizeFilename(fileName) + ".html");

And here 

if (Preference.get('datestampInLine')) {
        string += '<TITLE>Note from ' + dateString + '</TITLE>' + '\u000D\u000A' +  '<meta charset="utf-8' + '">' + '\u000D\u000A' + '' +  '\u000D\u000A';

Can you add it as "Save as HTML" in next release?

**Comment by bobbyrne01** [comment]
just to understand better, currently the addon allows users to save files as either `.txt` or `.csv`.

are you suggesting a third option i.e `.txt`, `.csv` or `.html`?

**Comment by Null-Kelvin** [comment]
Yes. It's quite useful when I need locally save instructions with html markup. When I save text with "As HTML" option, it's only logical to open it with browser instead of notepad.
But it also need some additions for save as valid html, like TITILE tag and charset meta-tag. I'm also add source url in comment.
My notes start with:
<TITLE>Note from 01-07-2015</TITLE>
<meta charset="utf-8">

**Comment by GreenLunar** [comment]
@Null-Kelvin is this what you want? [github.com_bobbyrne01_save-text-to-file-firefox.html.zip](https://github.com/bobbyrne01/save-text-to-file-firefox/files/7965831/github.com_bobbyrne01_save-text-to-file-firefox.html.zip)
