### ISSUE TITLE
It just stopped working…

### ISSUE THREAD

**Issue by uhjb** [bobbyrne01/save-text-to-file-firefox#81]
I've installed Save-text-to-file 2.6.9 for Firefox on a Mac a few days ago and it was working faultlessly. I enjoyed every moment using this wonderful add-on until a couple of days later when all of a sudden it stopped working. I've tried everything I could think of including uninstall and re-intall many many times without any success. I searched for similar problem others have experienced but didn't help. It just wouldn't work anymore. There's nothing when I right-click after selecting some text. Occasionally I could turn on the widget, but that didn't help neither. But I couldn't even turn the widget on the rest of the time. It seems to remember my preferences even after I've removed and re-installed it probably over 50 times by now. I'm just curious if there's a way to totally uninstall (absolutely remove) this add-on before another clean install. Or if you can show me where any related files are stored so I can manually delete them before another installation.
P.S. I do know how to use this add-on. I had it working for a couple of days. Thanks in advance.
George

**Comment by PointyWizardHat** [comment]
Hi, I'm also experiencing the same problem.
Using Save-text-to-file 2.6.9 on Cyberfox 39.0 64-bit on Win 8.1.

Save-text-to-file seemed to break after I upgraded Cyberfox from 38 to 39. I haven't added any other extensions/plug-ins etc. 

Cheers :)

**Comment by bobbyrne01** [comment]
Hey @PointyWizardHat , @uhjb I have not been able to reproduce the issue, as you can see from my screenshots below ..

![selection_176](https://cloud.githubusercontent.com/assets/1746110/8727618/975b9136-2bd8-11e5-8e12-6c97f8404c53.png)

![selection_177](https://cloud.githubusercontent.com/assets/1746110/8727624/9c3caeec-2bd8-11e5-805f-4622ffbff195.png)

### Possible workaround

To try resolve, on your systems could you try these steps ..
* open firefox
* tools, addons, remove 'save text to file'
* open `about:config`
* type `extensions.HighlightedTextToFile@bobbyrne01.org`
* right click on each of the entries shown in the screenshot below, and select `Reset`
* restart firefox
* try a new install of the addon

![selection_178](https://cloud.githubusercontent.com/assets/1746110/8727717/176c9c1c-2bd9-11e5-9809-825799da02df.png)

**Comment by uhjb** [comment]
Hi Robert,

Yes, that did it. The problem is fixed and is now working again. Thank 
you very much for your help.

**Comment by bobbyrne01** [comment]
glad to hear it, thanks for replying :+1:

**Comment by PointyWizardHat** [comment]
Fixed for me too, thanks.

**Comment by bobbyrne01** [comment]
your welcome :tada:
