### ISSUE TITLE
Returns ' Line Breaks Added when Confirm settings option NOT Checked

### ISSUE THREAD

**Issue by dd333** [bobbyrne01/save-text-to-file-firefox#83]
Great Addon.
Would be nice to use hotkey without having to click on Save button.
Would be nice to have as few returns as possible, especially if Line separator option is checked.
Thanks

Example of saved text when Confirm settings option is checked, and then not checked:
---------------------------------------------------------
https://github.com/bobbyrne01/save-text-to-file-firefox

userPreference--<todaysdate>.txt
userPreference--<timestamp>.txt
userPreference--<todaysdate>-<timestamp>.txt

---------------------------------------------------------
https://github.com/bobbyrne01/save-text-to-file-firefox

userPreference--<todaysdate>.txt

userPreference--<timestamp>.txt

userPreference--<todaysdate>-<timestamp>.txt

**Comment by bobbyrne01** [comment]
@dd333 could you please retest this on version v2.7.1?

**Comment by dd333** [comment]
Now able to uncheck confirm (just use hotkey) to append to save file -- without the added returns.
Bug apparently squashed ! ! 
Great addon.
Thanks

**Comment by bobbyrne01** [comment]
:wink:
