### ISSUE TITLE
Add ability save to md.

### ISSUE THREAD

**Issue by VVVi** [bobbyrne01/save-text-to-file-firefox#84]
Please, add ability save to md (MarkDown) format.

Thank you for the plug-in.

**Comment by bobbyrne01** [comment]
@VVVi currently you can save files with extension of `.txt` or `.csv`, are you simply looking for the addition of `.md` to that list?

**Comment by jonathan-s** [comment]
I would say yes @bobbyrne01, that is exactly what I'm looking for.

**Comment by bobbyrne01** [comment]
@VVVi @jonathan-s This is now available in version [4.2.0](https://addons.mozilla.org/en-GB/firefox/addon/save-text-to-file/).

**Comment by jonathan-s** [comment]
🙏
