### ISSUE TITLE
Port to WebExtensions

### ISSUE THREAD

**Issue by ssokolow** [bobbyrne01/save-text-to-file-firefox#85]
[Starting with Firefox 57](https://blog.mozilla.org/addons/2017/02/16/the-road-to-firefox-57-compatibility-milestones/), support for non-WebExtension-based extensions will be disabled.

That means that, if you want to avoid disruption for people on Aurora channel, a WebExtensions-based replacement has to be in place by [August 7th](https://wiki.mozilla.org/RapidRelease/Calendar) if you want to avoid disruption for Aurora-channel users.

The latest discussion I'm aware of around an API for filesystem access is in [bug 1246236](https://bugzilla.mozilla.org/show_bug.cgi?id=1246236) but, at present, the only way to do filesystem operations beyond "add a procedurally-generated file to the download manager with a suggested filename (inside the Downloads folder) and don't prompt for overwrite" is by installing a separate helper application and communicating with it through the [Native Messaging API](https://developer.chrome.com/extensions/nativeMessaging). This is the direction that [withExEditor](https://github.com/asamuzaK/withExEditor) has gone (see [withExEditorHost](https://github.com/asamuzaK/withExEditorHost)).

**Comment by yoyoma2** [comment]
Firefox 57 is coming.  Any chance of a WebExtensions version or is this the end of this extension?

**Comment by yoyoma2** [comment]
It seems this addon is not going to be ported to firefox 57 (quantum).  There is an addon "External Application Button" that works in firefox 57 (quantum) than can launch an application and send the url and selected text as arguments.  If you create a 'selection context' menu launcher with arguments [HREF] '[SELECTIONTEXT]' you can simulate savetexttofile behavior with a small script/batch file.

[scripts.zip](https://github.com/bobbyrne01/save-text-to-file-firefox/files/1494589/scripts.zip)

Installation is a bit of a pain but by tweaking the script you can approach your options' savetexttofile behavior.

**Comment by bobbyrne01** [comment]
try 3.0 ..

https://addons.mozilla.org/en-US/firefox/addon/save-text-to-file/versions/?page=1#version-3.0
