### ISSUE TITLE
This add on doesn't work for me.

### ISSUE THREAD

**Issue by phvrao** [bobbyrne01/save-text-to-file-firefox#86]
Hi,

I installed this on my Firefox version 56.0. I don't get to see the option "save text to file" in the context menu when I select the text and right click. I have tried using the Hot Key option as well. The text doesn't  get saved to the configured destination file. But I do see this add on in the Add-ons Manager.

Not sure what I am missing..Any help is highly appreciated.

Thanks.

**Comment by bobbyrne01** [comment]
Try 3.0 ..

https://addons.mozilla.org/en-US/firefox/addon/save-text-to-file/versions/?page=1#version-3.0
