### ISSUE TITLE
Mark version 3.0 as incompatible with Firefox 52

### ISSUE THREAD

**Issue by pickyusernamepicker** [bobbyrne01/save-text-to-file-firefox#88]
(and, if feasible, with Waterfox)
Now the new, necessarily crippled version is by default downloaded by anyone, including users of Firefox ESR on Windows XP or Waterfox, who can still use XUL add-ons.

**Comment by quarto505** [comment]
Desperately need revival of 'Append to text' & 'saved text separator' options. Please indicate if this are no longer possible. Using on Firefox57.02. TNX

**Comment by bobbyrne01** [comment]
@pickyusernamepicker this should be fixed in 3.0.1

@quarto505 I've opened 2 separate issues (#89 and #90) to track whether those features can be re-added, will let you know there.
