### ISSUE TITLE
saved text separator - in >3.0

### ISSUE THREAD

**Issue by bobbyrne01** [bobbyrne01/save-text-to-file-firefox#89]
fyi @quarto505

**Comment by aimanbaharum** [comment]
Still doing this? Really need this feature be implemented in latest Firefox.

I'd like to help, but can someone point to me where's the last working version as a reference that includes this feature, cuz I remember last time I used to use it to append texts in the same text file. Is there a browser limitation that makes the dev remove this feature? Thanks.

**Comment by bobbyrne01** [comment]
@quarto505 @aemxn This is now available again in latest release (4.1.0). Users can save (append) text to an existing file.

Please retest using latest install instructions here:

https://github.com/bobbyrne01/save-text-to-file-firefox#save-text-to-file-firefox

Or if you prefer Chrome, use:

https://github.com/bobbyrne01/save-text-to-file-chrome#save-text-to-file-chrome
