### ISSUE TITLE
Append to existing text file - in >3.0

### ISSUE THREAD

**Issue by bobbyrne01** [bobbyrne01/save-text-to-file-firefox#90]
fyi @quarto505

**Comment by sten9844** [comment]
Is this currently implemented? SttF 3.0.1 and FF 57.0.3 x64

**Comment by Dboingue** [comment]
Duplicate of #
https://github.com/bobbyrne01/save-text-to-file-firefox/issues/95#issue-310103527

**Comment by bobbyrne01** [comment]
@quarto505 @sten9844 This is now available again in latest release (4.1.0). Users can save (append) text to an existing file.

Please retest using latest install instructions here:

https://github.com/bobbyrne01/save-text-to-file-firefox#save-text-to-file-firefox
