### ISSUE TITLE
Alert is shown even though saving the file was aborted

### ISSUE THREAD

**Issue by tomtom** [bobbyrne01/save-text-to-file-firefox#91]
sttf always shows an alert (if "show alert" & if "show selection dialog" are enabled) even when the process was aborted.

0. Enable the two options
1. Select text
2. Wait for the dialog to appear
3. Press escape

The alert "Text saved to file" is displayed but not file was created.

sttf should check some return value of the dialog to see if a file was actually created.

**Comment by bobbyrne01** [comment]
should be available in [3.0.2](https://addons.mozilla.org/en-US/firefox/addon/save-text-to-file/versions/?page=1#version-3.0.2)
