### ISSUE TITLE
Feature reques: sanitized titel as file prefix (instead of a fixed prefix)

### ISSUE THREAD

**Issue by tomtom** [bobbyrne01/save-text-to-file-firefox#92]
Would it be possible to prefix a file with the page's title instead of a fix prefix? IMHO this would increase the usefulness of you addon dramatically.

Regards

**Comment by bobbyrne01** [comment]
should be in [3.1](https://addons.mozilla.org/en-US/firefox/addon/save-text-to-file/versions/?page=1#version-3.1)
