### ISSUE TITLE
Feature Request: Trigger auto save by a certain indicator

### ISSUE THREAD

**Issue by sten9844** [bobbyrne01/save-text-to-file-firefox#93]
If possible lets auto save a certain text identified by regular HTML tags as soon as the page is loaded/a button pressed and so one.

**Comment by bobbyrne01** [comment]
Can you give an example of how you would like to define such a rule?

**Comment by sten9844** [comment]
A few fancy things I would like to have:
- timed by hh, mm, ss
- setting xpath or simliar to auto save
- saving by an keyword
- if a title is shown

Something like this 😀

**Comment by bobbyrne01** [comment]
Outside the scope of future changes.
