### ISSUE TITLE
No text file saved

### ISSUE THREAD

**Issue by PGTips91** [bobbyrne01/save-text-to-file-firefox#94]
For some time now I have attempted to save selected text to file and while the addon goes through all the motions of creating and saving a text file to the selected directory, in fact nothing happens and there are no text files in the selected directory.

My system : --
 Linux Mint 18.1, based on
Linux version 4.4.0-83-generic (buildd@lgw01-29) (gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.4) ) #106-Ubuntu SMP Mon Jun 26 17:54:43 UTC 2017
Firefox Quantum 57.0.4 (64-bit) for Linux Mint 18.1
![screenshot at 2018-02-24 00-27-42](https://user-images.githubusercontent.com/30514088/36592235-bf830980-18f9-11e8-8dd2-afadc19b4568.png)
![screenshot at 2018-02-24 00-27-02](https://user-images.githubusercontent.com/30514088/36592236-bfb7eb3c-18f9-11e8-97bd-fa8b4fbe0a2f.png)
![screenshot at 2018-02-24 00-26-51](https://user-images.githubusercontent.com/30514088/36592238-bfe8e8c2-18f9-11e8-94b1-019e96e346f0.png)

**Comment by bobbyrne01** [comment]
which version of the addon are you using? and which version of firefox?

**Comment by simonjanosbalint** [comment]
OK, same problem here.
And no dir selection options, etc.
Always the latest version (Firefox, plugin). Now: Save text to file 3.1

I try a lot of filename prefix :\ 
(I don't know what is the default : ) 

![clipboard01](https://user-images.githubusercontent.com/11741449/37049383-0993cd50-2171-11e8-9866-7e0414735f3e.png)

**Comment by PGTips91** [comment]
I'm using Save text to file 3.1 and Firefox 57.0.4

It could be a bug in Firefox because I notice other apps not putting files where chosen, 
eg. in 'Downloads' rather than a  subdirectory that I chose.

**Comment by bobbyrne01** [comment]
fyi, from version `3.0` on-wards you can no longer select the directory to save the files, it defaults to the `Downloads` directory. This is a limitation from `Firefox`.

**Comment by PGTips91** [comment]
My issue is that the app goes through the motions of selecting a subdirectory, notifying the saving of the file but nothing really happens, there is no file saved.

With other apps the selection of a subdirectory is also simulated but there is a file saved in the standard directory.

**Comment by PGTips91** [comment]
Hi Robert,

Still getting only an error message, using version 3.2.4.

Regards,

Paul

**Comment by bobbyrne01** [comment]
Going to close this issue due to recent updates in the extension (4.1.0) and also lack of communication in this thread.

Please retest using latest install instructions here:

https://github.com/bobbyrne01/save-text-to-file-firefox#save-text-to-file-firefox

Or if you prefer Chrome, use:

https://github.com/bobbyrne01/save-text-to-file-chrome#save-text-to-file-chrome

**Comment by PGTips91** [comment]
I can confirm that it is now working in my Brave browser in Linux Mint 18.1

Paul

**Comment by PGTips91** [comment]
I have installed it also in Firefox 78.0.2, which I am no longer using and
it did not work there, with an error message.

I have read the instructions for installing the host application
https://github.com/bobbyrne01/save-text-to-file-firefox#installation
but as I am no longer using FF I have not gone any further.

Regards,
Paul
