### ISSUE TITLE
No "save text to file" after right click

### ISSUE THREAD

**Issue by lstar4ever** [bobbyrne01/save-text-to-file-firefox#96]
Hi,
This is a visually impaired person, with screen reader as my tool for navigating the computer.
After I ctrl+shift and right arrow to select some text
I press the application key of the keyboard to bring up the context menue, where there is no "save text to file" found.

I am not sure if it is not accessible via keyboard control or something wrong with my control.
If it is the problem with keyboard control. may you please consider about the accessibility and making possible fixes.
Many thanks.

**Comment by bobbyrne01** [comment]
hey @lstar4ever I've just tried v2 of Save Text to File using Firefox with a screen reader and the content menu item's text was indeed called out and executable. Could you please retry using the latest version? thanks
